const express = require('express');
const session = require('express-session');
const cookieParser = require('cookie-parser');
const bcrypt = require('bcrypt');
const path = require('path');
const db = require('./database');

const app = express();
const PORT = process.env.PORT || 3000;

// --- Middleware ---
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(session({
  secret: 'zaidan-machines-secret-key-2024',
  resave: false,
  saveUninitialized: false,
  cookie: { httpOnly: true, maxAge: 24 * 60 * 60 * 1000 } // 24 hours
}));

// --- Serve Static Files (Production Build) ---
// We serve the 'dist' folder which is generated by running `npm run build`
app.use(express.static(path.join(__dirname, 'dist')));

// --- Auth Middleware ---
const requireAdmin = (req, res, next) => {
  if (req.session && req.session.user && req.session.user.role === 'admin') {
    next();
  } else {
    res.status(403).json({ error: 'Forbidden' });
  }
};

// --- API Routes ---

// 1. Login
app.post('/api/login', (req, res) => {
  const { email, password } = req.body;
  
  db.get("SELECT * FROM users WHERE email = ?", [email], (err, user) => {
    if (err) return res.status(500).json({ error: 'Database error' });
    if (!user) return res.status(401).json({ error: 'Invalid credentials' });

    const validPass = bcrypt.compareSync(password, user.password);
    if (validPass) {
      req.session.user = { id: user.id, email: user.email, role: user.role };
      res.json({ success: true, user: { email: user.email, role: user.role } });
    } else {
      res.status(401).json({ error: 'Invalid credentials' });
    }
  });
});

// 2. Logout
app.post('/api/logout', (req, res) => {
  req.session.destroy();
  res.json({ success: true });
});

// 3. Get ERP Data (Protected)
app.get('/api/erp/data', requireAdmin, (req, res) => {
  const data = { customers: [], invoices: [], accounting: [] };

  db.serialize(() => {
    db.all("SELECT * FROM customers", [], (err, rows) => {
      if (err) return;
      data.customers = rows;
    });
    db.all("SELECT i.*, c.name as customerName FROM invoices i JOIN customers c ON i.customer_id = c.id", [], (err, rows) => {
      if (err) return;
      data.invoices = rows;
    });
    db.all("SELECT * FROM accounting ORDER BY date DESC", [], (err, rows) => {
      if (err) return;
      data.accounting = rows;
      // Send response after last query
      res.json(data);
    });
  });
});

// 4. Add Customer
app.post('/api/customers', requireAdmin, (req, res) => {
  const { name, phone } = req.body;
  const stmt = db.prepare("INSERT INTO customers (name, phone) VALUES (?, ?)");
  stmt.run(name, phone, function(err) {
    if (err) return res.status(500).json({ error: err.message });
    res.json({ id: this.lastID, name, phone, balance: 0 });
  });
  stmt.finalize();
});

// 5. Add Invoice
app.post('/api/invoices', requireAdmin, (req, res) => {
  const { customerId, machineType, amount, details } = req.body;
  const date = new Date().toISOString().split('T')[0];

  db.serialize(() => {
    // Insert Invoice
    const stmt = db.prepare("INSERT INTO invoices (customer_id, machine_type, amount, date, details) VALUES (?, ?, ?, ?, ?)");
    stmt.run(customerId, machineType, amount, date, details, function(err) {
      if (err) return res.status(500).json({ error: err.message });
      
      const invoiceId = this.lastID;

      // Update Customer Balance
      db.run("UPDATE customers SET balance = balance + ? WHERE id = ?", [amount, customerId]);

      // Add to Accounting (Income)
      const accStmt = db.prepare("INSERT INTO accounting (type, amount, description, date, timestamp) VALUES (?, ?, ?, ?, ?)");
      accStmt.run('income', amount, `Invoice #${invoiceId} - Machine: ${machineType}`, date, Date.now());
      accStmt.finalize();

      res.json({ success: true, invoiceId });
    });
    stmt.finalize();
  });
});

// 6. Add Accounting Entry
app.post('/api/accounting', requireAdmin, (req, res) => {
  const { type, amount, description } = req.body;
  const date = new Date().toISOString().split('T')[0];
  
  const stmt = db.prepare("INSERT INTO accounting (type, amount, description, date, timestamp) VALUES (?, ?, ?, ?, ?)");
  stmt.run(type, amount, description, date, Date.now(), function(err) {
    if (err) return res.status(500).json({ error: err.message });
    res.json({ success: true, id: this.lastID });
  });
  stmt.finalize();
});

// Catch all - Handle React Routing (SPA)
// Serve index.html for any request that doesn't match an API route or static file
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
  console.log(`Admin Login: EyadZidan110099@admin.com`);
});

